# DockerFile for the x86 on the cloud Virtual Server
FROM ubuntu

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y software-properties-common
RUN apt-get install -y \
    curl \
    git \
    python3.6 \
    python3-pip \
    python-opencv \
    python3-opencv \
    mosquitto \
    mosquitto-clients \
    vim \
    iputils-ping \
    libhdf5-dev \
    python3-numpy \
    python3-setuptools \
    python3-h5py \
    python3-wheel

RUN apt-get clean

RUN apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common

# add the docker repo
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
RUN add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"

# install it
RUN apt-get install docker-ce

RUN pip3 install paho-mqtt
RUN pip3 install opencv-python


RUN apt-get install automake autotools-dev g++ git libcurl4-openssl-dev libfuse-dev libssl-dev libxml2-dev make pkg-config
RUN git clone https://github.com/s3fs-fuse/s3fs-fuse.git
RUN cd s3fs-fuse
RUN ./autogen.sh
RUN ./configure
RUN make
RUN make install
