# DockerFile for the x86 on the cloud Virtual Server
FROM ubuntu

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y software-properties-common
RUN apt-get install -y \
    curl \
    git \
    python3.6 \
    python3-pip \
    python-opencv \
    python3-opencv \
    mosquitto \
    mosquitto-clients \
    vim \
    iputils-ping \
    libhdf5-dev \
    python3-numpy \
    python3-setuptools \
    python3-h5py \
    python3-wheel

RUN apt-get clean

RUN apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common

RUN pip3 install paho-mqtt
RUN pip3 install opencv-python
